"""“add_embeddings_metrics_tables”

Revision ID: 18eae95092ef
Revises: ffbb37ff7023
Create Date: 2025-04-15 13:43:42.925334

"""
from typing import Sequence, Union, Text

from alembic import op
import sqlalchemy as sa
from app.db.tables.commons.json_encoded_dict import JSONEncodedDict

# revision identifiers, used by Alembic.
revision: str = '18eae95092ef'
down_revision: Union[str, None] = 'ffbb37ff7023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_dataset_embeddings_metrics',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('CURRENT_UUID', sa.UUID(), nullable=False),
    sa.Column('METRICS', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('DRIFT', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['CURRENT_UUID'], ['current_dataset.UUID'], name=op.f('fk_current_dataset_embeddings_metrics_CURRENT_UUID_current_dataset')),
    sa.PrimaryKeyConstraint('UUID', name=op.f('pk_current_dataset_embeddings_metrics'))
    )
    op.create_table('reference_dataset_embeddings_metrics',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('REFERENCE_UUID', sa.UUID(), nullable=False),
    sa.Column('METRICS', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['REFERENCE_UUID'], ['reference_dataset.UUID'], name=op.f('fk_reference_dataset_embeddings_metrics_REFERENCE_UUID_reference_dataset')),
    sa.PrimaryKeyConstraint('UUID', name=op.f('pk_reference_dataset_embeddings_metrics'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_dataset_embeddings_metrics')
    op.drop_table('current_dataset_embeddings_metrics')
    # ### end Alembic commands ###
