"""set_correlation_id_optional

Revision ID: 3ec04e609ae9
Revises: 086f26392cc4
Create Date: 2024-07-08 10:28:35.068312

"""
from typing import Sequence, Union, Text

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec04e609ae9'
down_revision: Union[str, None] = '086f26392cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('current_dataset', 'CORRELATION_ID_COLUMN',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'current_dataset', ['UUID'])
    op.create_unique_constraint(None, 'current_dataset_metrics', ['UUID'])
    op.create_unique_constraint(None, 'reference_dataset', ['UUID'])
    op.create_unique_constraint(None, 'reference_dataset_metrics', ['UUID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference_dataset_metrics', type_='unique')
    op.drop_constraint(None, 'reference_dataset', type_='unique')
    op.drop_constraint(None, 'current_dataset_metrics', type_='unique')
    op.drop_constraint(None, 'current_dataset', type_='unique')
    op.alter_column('current_dataset', 'CORRELATION_ID_COLUMN',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
