"""“add_project_table”

Revision ID: 674d72dc789e
Revises: e72dc7aaa4cc
Create Date: 2025-03-10 11:42:03.851606

"""
from typing import Sequence, Union, Text

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674d72dc789e'
down_revision: Union[str, None] = 'e72dc7aaa4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('NAME', sa.VARCHAR(), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('DELETED', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('UUID', name=op.f('pk_project'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
