"""add percentage column

Revision ID: 750ad194c81a
Revises: 6edab3f23907
Create Date: 2024-10-16 15:20:12.688867

"""
from typing import Sequence, Union, Text

from alembic import op
import sqlalchemy as sa
from app.db.tables.commons.json_encoded_dict import JSONEncodedDict

# revision identifiers, used by Alembic.
revision: str = '750ad194c81a'
down_revision: Union[str, None] = '6edab3f23907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('NAME', sa.VARCHAR(), nullable=False),
    sa.Column('DESCRIPTION', sa.VARCHAR(), nullable=True),
    sa.Column('MODEL_TYPE', sa.VARCHAR(), nullable=False),
    sa.Column('DATA_TYPE', sa.VARCHAR(), nullable=False),
    sa.Column('GRANULARITY', sa.VARCHAR(), nullable=False),
    sa.Column('FEATURES', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('OUTPUTS', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('TARGET', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('TIMESTAMP', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('FRAMEWORKS', sa.VARCHAR(), nullable=True),
    sa.Column('ALGORITHM', sa.VARCHAR(), nullable=True),
    sa.Column('CREATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('DELETED', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('UUID'),
    schema='public'
    )
    op.create_table('current_dataset',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('MODEL_UUID', sa.UUID(), nullable=False),
    sa.Column('PATH', sa.VARCHAR(), nullable=False),
    sa.Column('DATE', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('CORRELATION_ID_COLUMN', sa.VARCHAR(), nullable=True),
    sa.Column('STATUS', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['MODEL_UUID'], ['public.model.UUID'], ),
    sa.PrimaryKeyConstraint('UUID'),
    schema='public'
    )
    op.create_table('reference_dataset',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('MODEL_UUID', sa.UUID(), nullable=False),
    sa.Column('PATH', sa.VARCHAR(), nullable=False),
    sa.Column('DATE', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('STATUS', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['MODEL_UUID'], ['public.model.UUID'], ),
    sa.PrimaryKeyConstraint('UUID'),
    schema='public'
    )
    op.create_table('current_dataset_metrics',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('CURRENT_UUID', sa.UUID(), nullable=False),
    sa.Column('MODEL_QUALITY', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('DATA_QUALITY', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('DRIFT', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('STATISTICS', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('PERCENTAGES', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['CURRENT_UUID'], ['public.current_dataset.UUID'], ),
    sa.PrimaryKeyConstraint('UUID'),
    schema='public'
    )
    op.create_table('reference_dataset_metrics',
    sa.Column('UUID', sa.UUID(), nullable=False),
    sa.Column('REFERENCE_UUID', sa.UUID(), nullable=False),
    sa.Column('MODEL_QUALITY', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('DATA_QUALITY', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.Column('STATISTICS', JSONEncodedDict(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['REFERENCE_UUID'], ['public.reference_dataset.UUID'], ),
    sa.PrimaryKeyConstraint('UUID'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_dataset_metrics', schema='public')
    op.drop_table('current_dataset_metrics', schema='public')
    op.drop_table('reference_dataset', schema='public')
    op.drop_table('current_dataset', schema='public')
    op.drop_table('model', schema='public')
    # ### end Alembic commands ###
