"""add percentage column

Revision ID: dccb82489f4d
Revises: 6edab3f23907
Create Date: 2024-10-17 09:03:48.063883

"""
from typing import Sequence, Union, Text

from alembic import op
import sqlalchemy as sa
from app.db.tables.commons.json_encoded_dict import JSONEncodedDict

# revision identifiers, used by Alembic.
revision: str = 'dccb82489f4d'
down_revision: Union[str, None] = '6edab3f23907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_dataset_metrics', sa.Column('PERCENTAGES', JSONEncodedDict(astext_type=Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_dataset_metrics', 'PERCENTAGES')
    # ### end Alembic commands ###
