default_language_version:
  python: python3.11
default_stages: [pre-commit, push]
exclude: >
  (?x)^(
      api/alembic|
      api/.venv|
      api/tests|
      sdk|
      spark|
      ui
  )$
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--config=api/pyproject.toml, --fix]
        files: ^((api/app)/.+)?[^/]+\.(py)$
      - id: ruff-format
        args: [--config=api/pyproject.toml]
        files: ^((api/app)/.+)?[^/]+\.(py)$