name: "Create a new task for Radicalbit AI Monitoring"
description: "Create a new task for Radicalbit AI Monitoring"
title: "As [Role] wants to [Action] in order to [Outcome] "
labels: "Feature+Request"
body:
- type: markdown
  attributes:
    value: Before you open a new task request, search through the existing task list to see if others have had the same idea.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have filled out the template to the best of my ability.
        required: true
      - label: This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
        required: true
      - label: This issue is not a duplicate feature request of [previous feature requests](https://github.com/radicalbit/radicalbit-ai-monitoring/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).
        required: true

- type: textarea
  attributes:
    label: "Please describe your task requirements"
    description: "A clear and concise description of what the task requirement is."
    placeholder: >
      Description:
      As a [Role], I want to [Action/Goal], so that [Benefit/Reason].
  validations:
    required: true

- type: textarea
  attributes:
    label: "Acceptance Criteria"
    description: "Acceptance Criteria"
    placeholder: > 
      ✅ The feature allows [User] to [Specific Action].
      ✅ The system provides [Expected Output or Behavior] when [Condition/Event].
      ✅ Error handling is implemented for [Edge Case/Scenario].
      ✅ The solution meets [Performance/Security/Usability] requirements.
      ✅ Tests cover [Unit/Integration/E2E] scenarios.
  validations:
    required: true

- type: textarea
  attributes:
    label: "Additional Notes"
    description: "Additional Notes"
    placeholder: > 
      [Any relevant information, such as dependencies or UI considerations]
  validations:
    required: false
