import { TABLE_COLOR } from '@Container/models/Details/constants';
import { numberFormatter } from '@Src/constants';
import { Truncate } from '@radicalbit/radicalbit-design-system';

export default [
  {
    title: '',
    key: 'className',
    dataIndex: 'className',
    onHeaderCell: () => ({ style: { background: 'transparent' } }),
    render: (label) => (
      <div className="font-[var(--coo-font-weight-bold)]">
        <Truncate>
          {label}
        </Truncate>
      </div>
    ),
  },
  {
    title: 'Precision',
    key: 'currentPrecision',
    dataIndex: 'currentPrecision',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: `${TABLE_COLOR.CURRENT_COLUMN}` } }),
    onHeaderCell: () => ({ style: { background: `${TABLE_COLOR.CURRENT_COLUMN}` } }),
    render: (currentPrecision) => numberFormatter().format(currentPrecision),
  },
  {
    title: 'Precision',
    key: 'referencePrecision',
    dataIndex: 'referencePrecision',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (referencePrecision) => numberFormatter().format(referencePrecision),
  },
  {
    title: 'Recall',
    key: 'currentRecall',
    dataIndex: 'currentRecall',
    align: 'right',
    width: '4rem',
    onCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    render: (currentRecall) => numberFormatter().format(currentRecall),
  },
  {
    title: 'Recall',
    key: 'referenceRecall',
    dataIndex: 'referenceRecall',
    align: 'right',
    width: '4rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (referenceRecall) => numberFormatter().format(referenceRecall),
  },
  {
    title: 'F1-Score',
    key: 'currentfMeasure',
    dataIndex: 'currentfMeasure',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    render: (currentfMeasure) => numberFormatter().format(currentfMeasure),
  },
  {
    title: 'F1-Score',
    key: 'referencefMeasure',
    dataIndex: 'referencefMeasure',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (referencefMeasure) => numberFormatter().format(referencefMeasure),
  },
  {
    title: 'True Positive Rate',
    key: 'currentTruePositiveRate',
    dataIndex: 'currentTruePositiveRate',
    align: 'right',
    width: '8rem',
    onCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    render: (currentTruePositiveRate) => numberFormatter().format(currentTruePositiveRate),
  },
  {
    title: 'True Positive Rate',
    key: 'referenceTruePositiveRate',
    dataIndex: 'referenceTruePositiveRate',
    align: 'right',
    width: '8rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (referenceTruePositiveRate) => numberFormatter().format(referenceTruePositiveRate),
  },
  {
    title: 'False Positive Rate',
    key: 'currentFalsePositiveRate',
    dataIndex: 'currentFalsePositiveRate',
    align: 'right',
    width: '8rem',
    onCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    render: (currentFalsePositiveRate) => numberFormatter().format(currentFalsePositiveRate),
  },
  {
    title: 'False Positive Rate',
    key: 'referenceFalsePositiveRate',
    dataIndex: 'referenceFalsePositiveRate',
    align: 'right',
    width: '8rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (referenceFalsePositiveRate) => numberFormatter().format(referenceFalsePositiveRate),
  },
  {
    title: 'Support',
    key: 'currentSupport',
    dataIndex: 'currentSupport',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    render: (currentSupport) => numberFormatter().format(currentSupport),
  },
  {
    title: 'Support',
    key: 'referenceSupport',
    dataIndex: 'referenceSupport',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (referenceSupport) => numberFormatter().format(referenceSupport),
  },
  {
    title: 'Support %',
    key: 'currentSupportPercent',
    dataIndex: 'currentSupportPercent',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.CURRENT_COLUMN } }),
    render: (currentSupportPercent) => `${numberFormatter().format(currentSupportPercent)}%`,
  },
  {
    title: 'Support %',
    key: 'referenceSupportPercent',
    dataIndex: 'referenceSupportPercent',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (referenceSupportPercent) => `${numberFormatter().format(referenceSupportPercent)}%`,
  },
];
