#!/bin/sh
# Update AUTHORS.md based on git history.

git log --reverse --format='%aN (<%aE>)' | perl -we '
BEGIN {
  %seen_names = ();
  %seen_emails = ();
}
while (<>) {
  my $line = $_;
  next if /(dependabot\[bot\])/;
  next if /(devops\@radicalbit.ai)/;
  next if /(devops\@users.noreply.github.com)/;

  # Extract the name before the email and convert to lowercase
  if ($line =~ /^(.+?) \((.+)\)$/) {
    my $name = lc($1);
    my $email = $2;
    # Skip if the name or email has been seen (case insensitive for name)
    next if $seen_names{$name}++;
    next if $seen_emails{$email}++;
  }

  push @authors, "- ", $line;
}
END {
  print "<!--\n";
  print "Copyright (c) radicalbit-ai-monitoring contributors.\n";
  print "Licensed under https://github.com/radicalbit/radicalbit-ai-monitoring/blob/main/LICENSE\n";
  print "-->\n\n";
  print "Contributors to radicalbit-ai-monitoring\n";
  print "============================\n";
  print "radicalbit-ai-monitoring is developed and maintained by a community of people interested in providing a comprehensive solution for monitoring your Machine Learning and Large Language Models in production.\n\n\n";
  print "<p align=\"center\">\n";
  print "<img src=\"https://contributors-img.web.app/image?repo=radicalbit/radicalbit-ai-monitoring\" width=\"500\"/>\n";
  print "</p>\n\n\n";
  print "Contributors (ordered by first contribution.)\n";
  print "-------------------------------------\n";
  print "[Full List of Contributors](https://github.com/radicalbit/radicalbit-ai-monitoring/graphs/contributors)\n\n";
  print @authors, "\n";
  print " ";
  print "#### Generated by tools/update-authors.sh.\n";
}
' > AUTHORS.md
