import { TABLE_COLOR } from '@Container/models/Details/constants';
import { numberFormatter } from '@Src/constants';

export default [
  {
    title: '',
    key: 'className',
    dataIndex: 'className',
    render: (label) => <div className="font-[var(--coo-font-weight-bold)]">{label}</div>,
  },
  {
    title: 'Precision',
    key: 'precision',
    dataIndex: 'precision',
    align: 'right',
    width: '10rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (precision) => numberFormatter().format(precision),
  },
  {
    title: 'Recall',
    key: 'recall',
    dataIndex: 'recall',
    align: 'right',
    width: '10rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (recall) => numberFormatter().format(recall),
  },
  {
    title: 'F1-Score',
    key: 'fMeasure',
    dataIndex: 'fMeasure',
    align: 'right',
    width: '10rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (fMeasure) => numberFormatter().format(fMeasure),
  },
  {
    title: 'True Positive Rate',
    key: 'truePositiveRate',
    dataIndex: 'truePositiveRate',
    align: 'right',
    width: '10rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (truePositiveRate) => numberFormatter().format(truePositiveRate),
  },
  {
    title: 'False Positive Rate',
    key: 'falsePositiveRate',
    dataIndex: 'falsePositiveRate',
    align: 'right',
    width: '10rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (falsePositiveRate) => numberFormatter().format(falsePositiveRate),
  },
  {
    title: 'Support',
    key: 'support',
    dataIndex: 'support',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (support) => numberFormatter().format(support),
  },
  {
    title: 'Support %',
    key: 'supportPercent',
    dataIndex: 'supportPercent',
    align: 'right',
    width: '5rem',
    onCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    onHeaderCell: () => ({ style: { background: TABLE_COLOR.REFERENCE_COLUMN } }),
    render: (supportPercent) => `${numberFormatter().format(supportPercent)}%`,
  },
];
