name: sdk-wf
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
    - "main"
    paths:
      - "sdk/**"
      - ".github/workflows/sdk-**"
  pull_request:
    branches:
    - "*"
    paths:
      - "sdk/**"
      - ".github/workflows/sdk-**"

env:
  POETRY_VERSION: "1.8.3"
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=${{ env.POETRY_VERSION }} python -
          poetry lock
      - name: Install dependencies
        run: |
          poetry install
      - name: Run formatting validation
        run: |
          poetry run ruff check
      - name: Run tests
        run: |
          poetry run pytest -v

  pypi-push:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./sdk
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=${{ env.POETRY_VERSION }} python -
          poetry lock
      - name: Publish to pypi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build
  